const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "919864620087";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "1єує" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "1єує",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "1єує",
  ownername:process.env.OWNER_NAME|| "1єує",

  sessionName:process.env.SESSION_ID || "SUHAIL_11_53_09_23_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDE4LFxuICAgICAgICAxODEsXG4gICAgICAgIDIxMixcbiAgICAgICAgNTYsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjU0LFxuICAgICAgICAzNSxcbiAgICAgICAgMTkyLFxuICAgICAgICAxMjgsXG4gICAgICAgIDQyLFxuICAgICAgICAyMTYsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTMwLFxuICAgICAgICAyMDMsXG4gICAgICAgIDc5LFxuICAgICAgICAxNzIsXG4gICAgICAgIDM3LFxuICAgICAgICAxMjEsXG4gICAgICAgIDU5LFxuICAgICAgICA5NCxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNTMsXG4gICAgICAgIDY2LFxuICAgICAgICAyNDgsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMzIsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMjIyLFxuICAgICAgICA1MSxcbiAgICAgICAgOTEsXG4gICAgICAgIDcwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDM2LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMTMyLFxuICAgICAgICAyNixcbiAgICAgICAgMTEwLFxuICAgICAgICAxODQsXG4gICAgICAgIDcxLFxuICAgICAgICAxNzcsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMjMsXG4gICAgICAgIDQ0LFxuICAgICAgICAxODUsXG4gICAgICAgIDUsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjEsXG4gICAgICAgIDI0LFxuICAgICAgICAyMzAsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjMxLFxuICAgICAgICAxOTIsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTEyLFxuICAgICAgICAxMTUsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTMsXG4gICAgICAgIDEsXG4gICAgICAgIDIzOCxcbiAgICAgICAgOTgsXG4gICAgICAgIDE4NyxcbiAgICAgICAgODZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzMixcbiAgICAgICAgMTM0LFxuICAgICAgICAyNDksXG4gICAgICAgIDE3LFxuICAgICAgICAxODIsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjQyLFxuICAgICAgICAxMTQsXG4gICAgICAgIDEyNSxcbiAgICAgICAgNDgsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMjA3LFxuICAgICAgICA1MyxcbiAgICAgICAgMTAsXG4gICAgICAgIDcyLFxuICAgICAgICAxNDUsXG4gICAgICAgIDY5LFxuICAgICAgICA1MyxcbiAgICAgICAgMjA1LFxuICAgICAgICAyMDksXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTgwLFxuICAgICAgICA3NyxcbiAgICAgICAgMTUsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjMzLFxuICAgICAgICAxMjMsXG4gICAgICAgIDgxLFxuICAgICAgICAxNDksXG4gICAgICAgIDM1LFxuICAgICAgICA1LFxuICAgICAgICA5M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDcsXG4gICAgICAgIDEyNixcbiAgICAgICAgNDAsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjQyLFxuICAgICAgICA5MCxcbiAgICAgICAgMzIsXG4gICAgICAgIDg1LFxuICAgICAgICAxNCxcbiAgICAgICAgMjQwLFxuICAgICAgICA3NCxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMTAsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTc2LFxuICAgICAgICA2MSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxNTcsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxMjEsXG4gICAgICAgIDUsXG4gICAgICAgIDU2LFxuICAgICAgICAxMTUsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNTEsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTAsXG4gICAgICAgIDQ2LFxuICAgICAgICAyNTUsXG4gICAgICAgIDkwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDgsXG4gICAgICAgIDgsXG4gICAgICAgIDMzLFxuICAgICAgICAxNjAsXG4gICAgICAgIDE0LFxuICAgICAgICAyMCxcbiAgICAgICAgNDQsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTkxLFxuICAgICAgICAyMTksXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjYsXG4gICAgICAgIDQ4LFxuICAgICAgICAyNTIsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMzksXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjUxLFxuICAgICAgICAxOTUsXG4gICAgICAgIDE5NyxcbiAgICAgICAgNjMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNTYsXG4gICAgICAgIDE0LFxuICAgICAgICAzNyxcbiAgICAgICAgOTIsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxNjYsXG4gICAgICAgIDIwNCxcbiAgICAgICAgNjAsXG4gICAgICAgIDEwMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3NSxcbiAgICAgICAgMjQ0LFxuICAgICAgICAxMCxcbiAgICAgICAgMTM3LFxuICAgICAgICAxMTgsXG4gICAgICAgIDcyLFxuICAgICAgICAyNTUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMjQyLFxuICAgICAgICA1MyxcbiAgICAgICAgMjQ1LFxuICAgICAgICA4NCxcbiAgICAgICAgMjQsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjI3LFxuICAgICAgICAxODksXG4gICAgICAgIDI0OCxcbiAgICAgICAgNjUsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMixcbiAgICAgICAgMTksXG4gICAgICAgIDEzMixcbiAgICAgICAgNDEsXG4gICAgICAgIDI5LFxuICAgICAgICAyNDcsXG4gICAgICAgIDczLFxuICAgICAgICAxNzgsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMjQsXG4gICAgICAgIDIsXG4gICAgICAgIDEwNSxcbiAgICAgICAgNDFcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDUzLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxMzksXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDExNlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1NyxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgODgsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDU0LFxuICAgICAgICAgIDY1XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTY0LFxuICAgICAgICAxMDQsXG4gICAgICAgIDU5LFxuICAgICAgICAxMzQsXG4gICAgICAgIDcyLFxuICAgICAgICAyMDcsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTE5LFxuICAgICAgICAxOTUsXG4gICAgICAgIDYxLFxuICAgICAgICAxMjksXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjUzLFxuICAgICAgICA5MCxcbiAgICAgICAgMTg4LFxuICAgICAgICAzMyxcbiAgICAgICAgNTYsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTUyLFxuICAgICAgICAxOTIsXG4gICAgICAgIDk5LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE0LFxuICAgICAgICAxODYsXG4gICAgICAgIDYwLFxuICAgICAgICA0NCxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNTksXG4gICAgICAgIDg2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgNTQsXG4gICAgICAgIDY0LFxuICAgICAgICAzMSxcbiAgICAgICAgMTA4LFxuICAgICAgICAxNDQsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTIyLFxuICAgICAgICA5MyxcbiAgICAgICAgMTgyLFxuICAgICAgICA2MixcbiAgICAgICAgMTc2LFxuICAgICAgICAyNTAsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTE5LFxuICAgICAgICAzMSxcbiAgICAgICAgMjE3LFxuICAgICAgICAyMzQsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNTksXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTk3LFxuICAgICAgICAzNyxcbiAgICAgICAgMTg5LFxuICAgICAgICAxMDksXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjE5LFxuICAgICAgICAyNDEsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjUyLFxuICAgICAgICA0MyxcbiAgICAgICAgNDAsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogODMsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiL3JLMFAxaEtrOS84SjlUWCtUMFl3MnphYWpFeHRiTDFNQnpoWjJZemwxTT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MTk4NjQ2MjAwODdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjkwMzRFMEE3RDRGQzA4NTdCQkIwNjFGNTU3MTc0M0Q1XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNzA5MjM4N1xuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkxOTg2NDYyMDA4N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMDE3MDEyMDA1NURBQjFGRTI0MzNFNjMyQjBERDI5RThcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI3MDkyMzg3XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIlRDUzlUaXhrVGwybnNrbEpMeWdqdHdcIixcbiAgXCJwaG9uZUlkXCI6IFwiMTYyYWU4MTQtOGJmYi00MTY0LThmMjYtYWQ4OGY4YzBkMzI4XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDg4LFxuICAgICAgNjIsXG4gICAgICAxMyxcbiAgICAgIDExOSxcbiAgICAgIDI1MixcbiAgICAgIDQsXG4gICAgICAxMzQsXG4gICAgICAyNyxcbiAgICAgIDE4OCxcbiAgICAgIDI0OCxcbiAgICAgIDI1NSxcbiAgICAgIDIzOSxcbiAgICAgIDEwNyxcbiAgICAgIDE5NSxcbiAgICAgIDI0OCxcbiAgICAgIDgzLFxuICAgICAgMzAsXG4gICAgICAyMjIsXG4gICAgICAxMTksXG4gICAgICAxMDVcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiB0cnVlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgODksXG4gICAgICAyMDIsXG4gICAgICAxMTUsXG4gICAgICAxOTEsXG4gICAgICAxNjgsXG4gICAgICA1MCxcbiAgICAgIDE4OSxcbiAgICAgIDIzMCxcbiAgICAgIDI0NCxcbiAgICAgIDQ0LFxuICAgICAgMjM1LFxuICAgICAgOTIsXG4gICAgICA3NCxcbiAgICAgIDY1LFxuICAgICAgMzQsXG4gICAgICAyNDAsXG4gICAgICAxOTUsXG4gICAgICAyMzgsXG4gICAgICA2NixcbiAgICAgIDE3MVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJOS0ZQSjFRN1wiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTE5ODY0NjIwMDg3OjE3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCI2NDUxNTEwNjQwODQzOjE3QGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIjHRlNGD0ZRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNLS20xNGtGRUp5dHhiY0dHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcImdCVnlqY1o2WGhkQUh2ejhHM2EraTdUWGxMUWlNRkw4eDJuUzJjTDVCaVk9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwieGNTeDdJeHBvMVBxbEthNUZCOElESVhXTFg4aU1VbHdtaXUrU0VVR2ZFbWNYdDgreExUY2IyRklWOUxMS3lMUVpiUngyUUNoa3J4NHU0WjZwRXdtRFE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiMDJvZzdXMHhTRjJyVy9sN1pjUTdxeWorcklUY3d5VUxpSDJZaUt4NG1OL2hrMWJKWTlSb1lWR1l3OGdmTmI3S2ZwV0RUMnh5TmtEZXhheElPdjlFREE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTE5ODY0NjIwMDg3OjE3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDIxLFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICA5NCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMjUyLFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICAzNCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAyNDksXG4gICAgICAgICAgNixcbiAgICAgICAgICAzOFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI3MDkyMzg0LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSXJRXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJclEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ1Y0IycHFjK0FkSWVEL0syR0swNVArUDlEZEVCWlZpb1AveFlQQmp1V1dJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEzNjI0ODE5NTQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyNzA5MjM4NzY3OFwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "1єує",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
